#Create Read Update Delete

#Programming courses

#Post   

#This is for creating an object
POST http://127.0.0.1:3000/api/courses/programming/ HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "title":"Learn CSS!",
    "language": "css",
    "views": 77777,
    "level": "basic"
}


###

#This is for editing completely an object
PUT  http://127.0.0.1:3000/api/courses/programming/2 HTTP/1.1
Content-Type: application/json

{
   "id": 2,
    "title":"Learn PHP!",
    "language": "php",
    "views": 777177,
    "level": "intermediate"
}

###

# This is for partially editing an object
PATCH http://127.0.0.1:3000/api/courses/programming/2
Content-Type: application/json

{
    "views": 600,
    "level": "Super mega pro"
}

###
#This is for deleting an object
DELETE http://127.0.0.1:3000/api/courses/programming/1 HTTP/1.1

#Maths courses

POST http://localhost:3000/api/courses/maths/ HTTP/1.1
Content-Type: application/json

{
    "id": 10,
    "title": "Diferential Equations",
    "subject": "calculus",
    "views": "12340",
    "level": "Advanced"
}

###

PUT http://localhost:3000/api/courses/maths/4 HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "title": "Linear Equations",
    "subject": "algebra",
    "views": "18350",
    "level": "Basic"
}

###

PATCH http://localhost:3000/api/courses/maths/4 HTTP/1.1
Content-Type: application/json

{   
    "title": "Linear Equations For Beginners",
    "views": 16000
}

###

DELETE http://localhost:3000/api/courses/maths/1 HTTP/1.1